version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - URI=914684874285.dkr.ecr.ap-southeast-1.amazonaws.com
      - ECR_REP_APP=dubicars_app
      - ECR_REP_NGINX=nginx
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $URI
  build:
    commands:
      - echo Build started on `date`
      # Build and push the laravel image
      - echo Building the Docker image...
      - docker build -t $ECR_REP_APP .
      - docker tag $ECR_REP_APP:latest $URI/$ECR_REP_APP:latest
      - docker push $URI/$ECR_REP_APP:latest

      # Build and push the nginx image
      - echo Building the Docker image...
      - cd ./nginx
      - docker build -t $ECR_REP_NGINX .
      - docker tag $ECR_REP_NGINX:latest $URI/$ECR_REP_NGINX:latest
      - docker push $URI/$ECR_REP_NGINX:latest
  post_build:
    commands:
      - echo Generating task-definition.json...
artifacts:
  files:
    - task-definition.json

