version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - URI=914684874285.dkr.ecr.ap-southeast-1.amazonaws.com
      - ECR_REP_APP=dubicars_app
      - ECR_REP_NGINX=nginx
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $URI
  build:
    commands:
      - echo Build started on `date`
      # Build and push the laravel image
      - echo Building the Docker image...
      - docker build -t $ECR_REP_APP .
      - docker tag $ECR_REP_APP:latest $URI/$ECR_REP_APP:latest
      - docker push $URI/$ECR_REP_APP:latest

      # Build and push the nginx image
      - echo Building the Docker image...
      - cd ./nginx
      - docker build -t $ECR_REP_NGINX .
      - docker tag $ECR_REP_NGINX:latest $URI/$ECR_REP_NGINX:latest
      - docker push $URI/$ECR_REP_NGINX:latest
  post_build:
    commands:
      - echo Generating task-definition.json...
      - |
        echo '{
          "containerDefinitions": [
            {
              "name": "laravel",
              "image": "'"$URI/'"$ECR_REP_APP"':latest",
              "cpu": 0,
              "portMappings": [{"name": "laravel-9000-tcp", "containerPort": 9000, "hostPort": 9000, "protocol": "tcp", "appProtocol": "http"}],
              "essential": true,
              "environment": [],
              "environmentFiles": [],
              "mountPoints": [],
              "volumesFrom": [],
              "ulimits": [],
              "logConfiguration": {"logDriver": "awslogs", "options": {"awslogs-create-group": "true", "awslogs-group": "/ecs/laravel-nginx", "awslogs-region": "'"ap-southeast-1"'", "awslogs-stream-prefix": "ecs"}, "secretOptions": []}
            },
            {
              "name": "nginx",
              "image": "'"$URI/$ECR_REP_NGINX:latest",
              "cpu": 0,
              "portMappings": [{"name": "nginx-80-tcp", "containerPort": 80, "hostPort": 80, "protocol": "tcp", "appProtocol": "http"}],
              "essential": true,
              "environment": [],
              "environmentFiles": [],
              "mountPoints": [],
              "volumesFrom": []
            }
          ],
          "family": "laravel-nginx",
          "networkMode": "awsvpc",
          "requiresAttributes": [{"name": "com.amazonaws.ecs.capability.logging-driver.awslogs"}, {"name": "ecs.capability.execution-role-awslogs"}, {"name": "com.amazonaws.ecs.capability.ecr-auth"}, {"name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"}, {"name": "ecs.capability.execution-role-ecr-pull"}, {"name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"}, {"name": "ecs.capability.task-eni"}, {"name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"}],
          "placementConstraints": [],
          "compatibilities": ["EC2", "FARGATE"],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "3072",
          "runtimePlatform": {"cpuArchitecture": "X86_64", "operatingSystemFamily": "LINUX"}
        }' > task-definition.json
artifacts:
  files:
    - task-definition.json

