version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI_NGINX=914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building Nginx Docker image...
      - cd ./nginx
      - docker build -t $REPOSITORY_URI_NGINX:latest .
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Nginx Docker images...
      - docker push $REPOSITORY_URI_NGINX:latest
      - docker push $REPOSITORY_URI_NGINX:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI_NGINX:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: dubicars-nginx-pipel/imagedefinitions.json
