version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-web-app
    container_name: laravel-web-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    networks:
      - laravel-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: laravel-web-server
    container_name: laravel-web-server
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge