FROM 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest

# Copy nginx configurations
# COPY default.conf /etc/nginx/conf.d/

# # Expose port
# EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]