name: Trigger on Pull Request Comment

on:
  issue_comment:
    types:
      - "created"
jobs:
  check_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v5
        with:
          script:
            github.event.issue.pull_request && contains(github.event.comment.body, '/test')

      - name: Login to AWS
        if: success()
        uses: aws-actions/aws-login@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Run Build Docker build t
        if: success()
        run: |
          docker build -t 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/dubicars_app:latest .
      
      - name: Push Image to ECR
        if: success()
        run: |
          docker push 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/dubicars_app:latest

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: github.event.issue.number,
              owner: github.repo.owner,
              repo: github.repo.repo,
              body: 'Build or deployment failed!'
            })