name: Trigger on Pull Request Comment

on:
  issue_comment:
    types:
      - "created"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/staging') # checks if the comments come from pull request and not from an issue
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.TOKEN_GITHUB }}
          status: pending

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Deploy Staging
        if: contains(github.event.comment.body, '/staging')   # check the comment if it contains the keywords
        run: |
          echo Build for staging
      - name: Deploye dev
        if: contains(github.event.comment.body, '/dev')  # check the comment if it contains the keywords
        run: |
          echo Build for test stage

      # - name: GitHub Script
      #   uses: actions/github-script@v5
      #   with:
      #     script: |

      #       if (github.event.issue.pull_request && github.event.comment.body.includes('/test')){
      #         console.log('Conditions met!');
      #         process.exit(0)
      #       } else {
      #         console.log('Conditions not met');
      #         process.exit(78)
      #       }

      # - name: Configure AWS credentials
      #   if: success()
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      # - name: Run Build Docker build
      #   if: success()
      #   run: |
      #     docker build -t 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/dubicars_app:latest .
      
      # - name: Push Image to AWS ECR
      #   if: success()
      #   run: |
      #     docker push 914684874285.dkr.ecr.ap-southeast-1.amazonaws.com/dubicars_app:latest

      # - name: Notify on failure
      #   if: failure()
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.issues.createComment({
      #         issue_number: github.event.issue.number,
      #         owner: github.repo.owner,
      #         repo: github.repo.repo,
      #         body: 'Build or deployment failed!'
      #       })